INSERT INTO schedules (text, day) VALUES 
('08:45 - 12:00 ; 13:30 - 17:15', 'Lundi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mardi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mercredi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Jeudi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Vendredi'),
('08:45 - 12:00', 'Samedi'),
('Fermé', 'Dimanche');

INSERT INTO motor_technologies (property) VALUES ('Essence');
INSERT INTO motor_technologies (property) VALUES ('Diesel');
INSERT INTO motor_technologies (property) VALUES ('Électrique');
INSERT INTO motor_technologies (property) VALUES ('Hybride');
INSERT INTO motor_technologies (property) VALUES ('GPL');
INSERT INTO motor_technologies (property) VALUES ('Éthanol');
INSERT INTO motor_technologies (property) VALUES ('Autres');

INSERT INTO services (title, text, picture) VALUES 
('Réparation de mécanique générale', 
'Notre garage offre une expertise pointue en réparations mécaniques, résolvant efficacement les 
problèmes liés au moteur, à la transmission et à d''autres composants essentiels. Nous diagnostiquons 
avec précision et réparons rapidement pour vous remettre sur la route en toute sécurité.',
'mecanique.jpg'),
('Entretien périodique', 
'Assurer la longévité de votre véhicule est notre priorité. Notre service d''entretien périodique 
comprend des vérifications rigoureuses, des changements d''huile réguliers et une maintenance préventive 
pour garantir des performances optimales et réduire les risques de pannes inattendues.',
'entretien.jpg'),
('Service de climatisation', 
'La fraîcheur dans votre voiture est cruciale. Notre équipe spécialisée offre un service complet de 
climatisation, du diagnostic des problèmes de refroidissement à la réparation des fuites, 
assurant un confort optimal dans votre véhicule par tous les temps.',
'climatisation.jpg'),
('Réparation et remplacement des pneus', 
'Des pneus en bon état sont essentiels pour une conduite sûre. Nous proposons des services de 
réparation de pneus crevés, d''alignement, et de remplacement, avec une gamme de marques et de modèles 
pour répondre à vos besoins spécifiques.',
'pneus.jpg'),
('Réparation de la carrosserie', 
'Des bosses aux éraflures, notre équipe de réparation de carrosserie redonne à votre véhicule son 
aspect d''origine. Nous utilisons des techniques avancées pour restaurer la carrosserie, vous offrant 
un résultat impeccable et une voiture qui brille comme neuve.',
'carrosserie.jpg'),
('Vente de véhicules d''occasions', 
'Explorez notre inventaire complet de véhicules d''occasion, rigoureusement inspectés pour assurer 
fiabilité et performance. Notre équipe experte vous guide dans le choix du véhicule idéal, en mettant 
l''accent sur la transparence et la qualité. Trouvez ici votre prochaine voiture en toute confiance !',
'occasion.jpg');

INSERT INTO reviews (firstname, lastname, text, approved, service_id, rate) VALUES 
('John', 
'Doe',
'La réparation de mécanique était rapide et efficace, mon véhicule fonctionne comme neuf!',
false,
7,
5),
('Bruce', 
'Wayne',
'L''entretien périodique est toujours impeccable. Mon véhicule est entre de bonnes mains.',
true,
8,
4),
('Tony', 
'Stark',
'Le service de climatisation a rendu ma conduite estivale très agréable. Fraîcheur garantie!',
false,
9,
5),
('Harry', 
'Potter',
'J''ai fait réparer et remplacer mes pneus ici. Ils ont fait un excellent travail et sont très rapides.',
false,
10,
5),
('Ron', 
'Wesley',
'Après un accident, la réparation de la carrosserie était parfaite. Ma voiture est comme neuve.',
true,
11,
4),
('Catherine', 
'Bernaud',
'J''ai acheté une voiture ici et je suis ravi ! En parfait état, conforme à la description. 
Le personnel était serviable et honnête. Une expérience d''achat très satisfaisante.',
true,
12,
3);

INSERT INTO brands (property) VALUES 
('Acura'),
('Alfa Romeo'),
('Aston Martin'),
('Audi'),
('Bentley'),
('BMW'),
('Bugatti'),
('Buick'),
('Cadillac'),
('Chery'),
('Chevrolet'),
('Chrysler'),
('Citroën'),
('Dacia'),
('Daewoo'),
('Daihatsu'),
('Dodge'),
('Ferrari'),
('Fiat'),
('Ford'),
('Geely'),
('Genesis'),
('GMC'),
('Great Wall'),
('Haval'),
('Honda'),
('Hummer'),
('Hyundai'),
('Infiniti'),
('Isuzu'),
('Jaguar'),
('Jeep'),
('Kia'),
('Lada'),
('Lamborghini'),
('Lancia'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Lotus'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes-Benz'),
('Mercury'),
('MG'),
('Mini'),
('Mitsubishi'),
('Nissan'),
('Opel'),
('Pagani'),
('Peugeot'),
('Pontiac'),
('Porsche'),
('Proton'),
('Ram'),
('Renault'),
('Rolls-Royce'),
('Saab'),
('Saturn'),
('Škoda'),
('Smart'),
('SsangYong'),
('Subaru'),
('Suzuki'),
('Tata'),
('Tesla'),
('Toyota'),
('Vauxhall'),
('Volkswagen'),
('Volvo'),
('ZAZ');