INSERT INTO schedules (text, day) VALUES 
('08:45 - 12:00 ; 13:30 - 17:15', 'Lundi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mardi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mercredi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Jeudi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Vendredi'),
('08:45 - 12:00', 'Samedi'),
('Fermé', 'Dimanche');

INSERT INTO motor_technologies (property) VALUES ('Essence');
INSERT INTO motor_technologies (property) VALUES ('Diesel');
INSERT INTO motor_technologies (property) VALUES ('Électrique');
INSERT INTO motor_technologies (property) VALUES ('Hybride');
INSERT INTO motor_technologies (property) VALUES ('GPL');
INSERT INTO motor_technologies (property) VALUES ('Éthanol');

INSERT INTO brands (property) VALUES 
('Acura'),
('Alfa Romeo'),
('Aston Martin'),
('Audi'),
('Bentley'),
('BMW'),
('Bugatti'),
('Buick'),
('Cadillac'),
('Chery'),
('Chevrolet'),
('Chrysler'),
('Citroën'),
('Dacia'),
('Daewoo'),
('Daihatsu'),
('Dodge'),
('Ferrari'),
('Fiat'),
('Ford'),
('Geely'),
('Genesis'),
('GMC'),
('Great Wall'),
('Haval'),
('Honda'),
('Hummer'),
('Hyundai'),
('Infiniti'),
('Isuzu'),
('Jaguar'),
('Jeep'),
('Kia'),
('Lada'),
('Lamborghini'),
('Lancia'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Lotus'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes-Benz'),
('Mercury'),
('MG'),
('Mini'),
('Mitsubishi'),
('Nissan'),
('Opel'),
('Pagani'),
('Peugeot'),
('Pontiac'),
('Porsche'),
('Proton'),
('Ram'),
('Renault'),
('Rolls-Royce'),
('Saab'),
('Saturn'),
('Škoda'),
('Smart'),
('SsangYong'),
('Subaru'),
('Suzuki'),
('Tata'),
('Tesla'),
('Toyota'),
('Vauxhall'),
('Volkswagen'),
('Volvo'),
('ZAZ');