INSERT INTO schedules (text, day) VALUES 
('08:45 - 12:00 ; 13:30 - 17:15', 'Lundi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mardi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Mercredi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Jeudi'),
('08:45 - 12:00 ; 13:30 - 17:15', 'Vendredi'),
('08:45 - 12:00', 'Samedi'),
('Fermé', 'Dimanche');

INSERT INTO motor_technologies (property) VALUES ('Essence');
INSERT INTO motor_technologies (property) VALUES ('Diesel');
INSERT INTO motor_technologies (property) VALUES ('Électrique');
INSERT INTO motor_technologies (property) VALUES ('Hybride');
INSERT INTO motor_technologies (property) VALUES ('GPL');
INSERT INTO motor_technologies (property) VALUES ('Éthanol');
INSERT INTO motor_technologies (property) VALUES ('Autres');


INSERT INTO reviews (firstname, lastname, text, approved, service_id, rate) VALUES 
('John', 
'Doe',
'La réparation de mécanique était rapide et efficace, mon véhicule fonctionne comme neuf!',
false,
21,
5),
('Bruce', 
'Wayne',
'L''entretien périodique est toujours impeccable. Mon véhicule est entre de bonnes mains.',
true,
22,
4),
('Tony', 
'Stark',
'Le service de climatisation a rendu ma conduite estivale très agréable. Fraîcheur garantie!',
false,
23,
5),
('Harry', 
'Potter',
'J''ai fait réparer et remplacer mes pneus ici. Ils ont fait un excellent travail et sont très rapides.',
false,
24,
5),
('Ron', 
'Wesley',
'Après un accident, la réparation de la carrosserie était parfaite. Ma voiture est comme neuve.',
true,
25,
4),
('Catherine', 
'Bernaud',
'J''ai acheté une voiture ici et je suis ravi ! En parfait état, conforme à la description. 
Le personnel était serviable et honnête. Une expérience d''achat très satisfaisante.',
true,
26,
3);

INSERT INTO brands (property) VALUES 
('Acura'),
('Alfa Romeo'),
('Aston Martin'),
('Audi'),
('Bentley'),
('BMW'),
('Bugatti'),
('Buick'),
('Cadillac'),
('Chery'),
('Chevrolet'),
('Chrysler'),
('Citroën'),
('Dacia'),
('Daewoo'),
('Daihatsu'),
('Dodge'),
('Ferrari'),
('Fiat'),
('Ford'),
('Geely'),
('Genesis'),
('GMC'),
('Great Wall'),
('Haval'),
('Honda'),
('Hummer'),
('Hyundai'),
('Infiniti'),
('Isuzu'),
('Jaguar'),
('Jeep'),
('Kia'),
('Lada'),
('Lamborghini'),
('Lancia'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Lotus'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes-Benz'),
('Mercury'),
('MG'),
('Mini'),
('Mitsubishi'),
('Nissan'),
('Opel'),
('Pagani'),
('Peugeot'),
('Pontiac'),
('Porsche'),
('Proton'),
('Ram'),
('Renault'),
('Rolls-Royce'),
('Saab'),
('Saturn'),
('Škoda'),
('Smart'),
('SsangYong'),
('Subaru'),
('Suzuki'),
('Tata'),
('Tesla'),
('Toyota'),
('Vauxhall'),
('Volkswagen'),
('Volvo'),
('ZAZ');